// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Semester6_DiceCode4.Data;

#nullable disable

namespace Semester6_DiceCode4.Migrations
{
    [DbContext(typeof(ASPEC06DBContext))]
    partial class ASPEC06DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Semester6_DiceCode4.Models.CijferWijziging", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("NieuwCijfer")
                        .HasColumnType("int");

                    b.Property<int?>("OudCijfer")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("ToetsId")
                        .HasColumnType("int");

                    b.Property<int>("VakId")
                        .HasColumnType("int");

                    b.Property<DateTime>("WijzigingsDatum")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CijferWijzigingen");
                });

            modelBuilder.Entity("Semester6_DiceCode4.Models.Docent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Docenten");
                });

            modelBuilder.Entity("Semester6_DiceCode4.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Studenten");
                });

            modelBuilder.Entity("Semester6_DiceCode4.Models.StudentVak", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("VakId")
                        .HasColumnType("int");

                    b.HasKey("StudentId", "VakId");

                    b.HasIndex("VakId");

                    b.ToTable("StudentVakken");
                });

            modelBuilder.Entity("Semester6_DiceCode4.Models.Toets", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Cijfer")
                        .HasColumnType("float");

                    b.Property<bool>("Herkansing")
                        .HasColumnType("bit");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("VakId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("VakId");

                    b.ToTable("Toetsen");
                });

            modelBuilder.Entity("Semester6_DiceCode4.Models.Vak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocentId")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocentId");

                    b.ToTable("Vakken");
                });

            modelBuilder.Entity("Semester6_DiceCode4.Models.StudentVak", b =>
                {
                    b.HasOne("Semester6_DiceCode4.Models.Student", "Student")
                        .WithMany("StudentVakken")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Semester6_DiceCode4.Models.Vak", "Vak")
                        .WithMany("StudentVakken")
                        .HasForeignKey("VakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Vak");
                });

            modelBuilder.Entity("Semester6_DiceCode4.Models.Toets", b =>
                {
                    b.HasOne("Semester6_DiceCode4.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Semester6_DiceCode4.Models.Vak", "Vak")
                        .WithMany("Toetsen")
                        .HasForeignKey("VakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Vak");
                });

            modelBuilder.Entity("Semester6_DiceCode4.Models.Vak", b =>
                {
                    b.HasOne("Semester6_DiceCode4.Models.Docent", "Docent")
                        .WithMany("Vakken")
                        .HasForeignKey("DocentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Docent");
                });

            modelBuilder.Entity("Semester6_DiceCode4.Models.Docent", b =>
                {
                    b.Navigation("Vakken");
                });

            modelBuilder.Entity("Semester6_DiceCode4.Models.Student", b =>
                {
                    b.Navigation("StudentVakken");
                });

            modelBuilder.Entity("Semester6_DiceCode4.Models.Vak", b =>
                {
                    b.Navigation("StudentVakken");

                    b.Navigation("Toetsen");
                });
#pragma warning restore 612, 618
        }
    }
}
